AllCops:
  TargetRubyVersion: 2.6

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/LineLength:
  Enabled: true
  AutoCorrect: true
  IgnoredPatterns: ['\A\s*#']

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/BlockComments:
  Enabled: false

Style/BlockDelimiters:
  Enabled: true
  EnforcedStyle: 'semantic'

Style/Documentation:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/RegexpLiteral:
  Enabled: true
  EnforcedStyle: percent_r

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true
