language: ruby

rvm:
  - 2.6.5


before_install:
  - gem install bundler
  - gem install rubocop

bundler_args: --without production --without development

services:
  - postgresql

before_script:
  - psql -U postgres -c "CREATE USER $RUBY_DB_USER WITH CREATEDB LOGIN ENCRYPTED PASSWORD '$DB_PW'"

script:
  - bundle exec rubocop -F
  - bundle exec rspec
  - bundle exec cucumber
