language: ruby

rvm:
  - 2.6.5


before_install:
  - sudo apt-get update -y && sudo apt-get install -y libsodium-dev
  - gem install bundler
  - gem install rubocop

services:
  - postgresql

before_script:
  - psql -U postgres -c "CREATE DATABASE user_management_test;"
  - psql -U postgres -c "CREATE USER $RUBY_DB_USER WITH CREATEDB LOGIN ENCRYPTED PASSWORD '$DB_PW';"

script:
  - rubocop -F
  - RAILS_ENV=test bundle exec rails db:setup && RAILS_ENV=test bundle exec rails db:migrate && bundle exec rspec && bundle exec cucumber
