language: ruby

os:
  - linux

dist: xenial

cache:
 directories:
    - /home/travis/.rvm/
    - /home/travis/.bundle/

rvm:
  - 2.6.5

env:
  - RUBY_DB_USER=cicdtest DB_PW=widner

before_install:
  - sudo apt-get update -y && sudo apt-get install -y libsodium-dev
  - gem install bundler
  - gem install rubocop

services:
  - postgresql

before_script:
  - psql -U postgres -c "CREATE USER $RUBY_DB_USER WITH CREATEDB LOGIN ENCRYPTED PASSWORD '$DB_PW'"
  - RAILS_ENV=test bundle exec rails db:setup && RAILS_ENV=test bundle exec rails db:migrate

script:
  - bundle exec rails s & bundle exec rubocop -F -L app lib spec config features && bundle exec rspec && bundle exec cucumber
