default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  username: <%= ENV.fetch('RUBY_DB_USER') %>
  password: <%= ENV.fetch('DB_PW') %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: user_management_development

test:
  <<: *default
  database: user_management_test

production:
  <<: *default
  database: user_management_production
